trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Ensure Docker is available
- task: Bash@3
  displayName: 'Verify Docker Installation'
  inputs:
    targetType: 'inline'
    script: |
      echo "Checking Docker installation..."
      if ! command -v docker &> /dev/null; then
        echo "Docker not found. Installing Docker..."
        sudo apt-get update
        sudo apt-get install -y docker.io
      else
        echo "Docker is already installed."
      fi
      docker --version

# Step 2: Pull Docker Image
- task: Bash@3
  displayName: 'Pull Docker Image'
  inputs:
    targetType: 'inline'
    script: |
      echo "Pulling Docker image: chandra635313/spring-boot-mongo:latest"
      docker pull chandra635313/spring-boot-mongo:latest

# Step 3: Install Trivy and Scan Docker Image
- task: Bash@3
  displayName: 'Scan Docker Image with Trivy'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Trivy..."
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      export PATH=$PATH:$(pwd)/bin
      trivy --version

      echo "Running Trivy scan and saving report..."
      trivy image --format html --output trivy-report.html chandra635313/spring-boot-mongo:latest

      echo "Scan complete. Report generated: trivy-report.html"

# Step 4: Publish Trivy Scan Report
- task: PublishPipelineArtifact@1
  displayName: 'Publish Trivy Scan Report'
  inputs:
    targetPath: 'trivy-report.html'
    artifact: 'TrivyReport'
    publishLocation: 'pipeline'
