trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'tomcat'
  IMAGE_TAG: 'latest'

steps:

# Step 1: Install Docker (Ubuntu agents usually have Docker, but just in case)
- task: Bash@3
  displayName: 'Install Docker'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Docker..."
      sudo apt-get update
      sudo apt-get install -y docker.io
      docker --version

# Step 2: Pull Docker image
- task: Bash@3
  displayName: 'Pull Docker Image'
  inputs:
    targetType: 'inline'
    script: |
      echo "Pulling Docker image: $(IMAGE_NAME):$(IMAGE_TAG)"
      docker pull $(IMAGE_NAME):$(IMAGE_TAG)

# Step 3: Install Trivy
- task: Bash@3
  displayName: 'Install Trivy'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Trivy..."
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      export PATH=$PATH:$(pwd)/bin
      trivy --version

- task: Bash@3
  displayName: 'Install and Scan Docker Image with Trivy'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Trivy..."
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Add Trivy to PATH
      export PATH=$PATH:$(pwd)/bin

      trivy --version

      echo "Pulling Docker image: nginx:latest"
      docker pull tomcat:latest

      echo "Scanning Docker image for vulnerabilities..."
      trivy image --exit-code 0 --severity HIGH,CRITICAL tomcat:latest
