trigger:
  - main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu agent

variables:
  IMAGE_NAME: 'nginx'        # Docker image name
  IMAGE_TAG: 'latest'        # Docker image tag

steps:

# Step 1: Pull Docker Image
- task: Bash@3
  displayName: 'Pull Docker Image'
  inputs:
    targetType: 'inline'
    script: |
      echo "Pulling Docker image: $(IMAGE_NAME):$(IMAGE_TAG)"
      docker pull $(IMAGE_NAME):$(IMAGE_TAG)


