trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'chandra635313/spring-boot-mongo'
  IMAGE_TAG: 'latest'

steps:

# Step 1: Ensure Docker is available
- task: Bash@3
  displayName: 'Verify Docker Installation'
  inputs:
    targetType: 'inline'
    script: |
      echo "Checking Docker installation..."
      if ! command -v docker &> /dev/null; then
        echo "Docker not found. Installing Docker..."
        sudo apt-get update
        sudo apt-get install -y docker.io
      else
        echo "Docker is already installed."
      fi
      docker --version

# Step 2: Pull Docker image
- task: Bash@3
  displayName: 'Pull Docker Image'
  inputs:
    targetType: 'inline'
    script: |
      echo "Pulling Docker image: $(IMAGE_NAME):$(IMAGE_TAG)"
      docker pull $(IMAGE_NAME):$(IMAGE_TAG)

# Step 3: Install and Run Trivy Scan
- task: Bash@3
  displayName: 'Scan Docker Image with Trivy'
  inputs:
    targetType: 'inline'
    script: |
      echo "Installing Trivy..."
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      echo "Adding Trivy to PATH..."
      export PATH=$PATH:$(pwd)/bin

      trivy --version

      echo "Scanning Docker image for vulnerabilities..."
      trivy image --exit-code 0 --severity HIGH,CRITICAL $(IMAGE_NAME):$(IMAGE_TAG)
