trigger: none  # Run manually

parameters:
  - name: reportDate
    displayName: 'Report Date (YYYY-MM-DD)'
    type: string
    default: '2025-05-06'

variables:
  S3_BUCKET_NAME: appsec-mss-prod-accenturecio-now

pool:
  vmImage: 'windows-latest'  # ✅ Fixed: Use Microsoft-hosted agent

steps:
  - task: PowerShell@2
    displayName: 'Install AWS CLI'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Installing AWS CLI..."
        $Installer = "$env:TEMP\AWSCLIV2.msi"
        Invoke-WebRequest "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile $Installer
        Start-Process msiexec.exe -ArgumentList "/i `"$Installer
